### ISSUE TITLE
Patch: Fix SQLiteCursor locking issue.

### ISSUE THREAD

**Issue by promeG** [sqlcipher/android-database-sqlcipher#114]
Hi, I have encountered deadlock problem when applying SQLCipher to my application.

There is a closed issue about it : https://github.com/sqlcipher/android-database-sqlcipher/issues/97

I compared the lock method used in SQLCipher with AOSP4.0.1, and found that there are some difference.

After doing some changes, I finally get rid of deadlock problem. Here is the patch: https://github.com/promeG/SQLCipher-Android-Fix-Deadlock-Patch

I hope it  can help with other people who have the same problem.

SQLCipher is a great project, thank you for your hard work!

**Comment by narakim** [comment]
I also have the same issue too. :-( Did anyone figure this out??

**Comment by baskarsk** [comment]
Hi ,

I am getting the following Exception trace

"java.util.concurrent.TimeoutException: net.sqlcipher.database.SQLiteCompiledSql.finalize() timed out after 10 seconds"

I looked into the Sqlcipher code and found the Reentrantlock causing problem while the GC running.

Is there any way to fix this timeout issue? 

Will the setLockingEnabled(false) & the yieldIfContendedSafely() will work ?

**Comment by developernotes** [comment]
Hello @baskarsk 

Can you create a reproducible test in the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

**Comment by baskarsk** [comment]
@developernotes ,

Thanks for the reply,.

The issue is araising very rarely, i couldn't get the exact clue why it is happening. One debug scenario is , i left my device idle (Screen lock) for few hours and opening the app and doing a DB operation.

From the below link you could find the exact statment on timeout Exception in Idle state.(Which matches my scenario too)

"http://stackoverflow.com/questions/24021609/how-to-handle-java-util-concurrent-timeoutexception-android-os-binderproxy-fin"  

Could you assist on this, meanwhile i run the Test Application and update on that.

**Comment by gunC** [comment]
Hi ,

I am getting the following Exception trace

"java.util.concurrent.TimeoutException: net.sqlcipher.database.SQLiteCompiledSql.finalize() timed out after 10 seconds"

if I use "android.databse.sqlite" then app run normally.

```
    db.beginTransaction();
    for(...){// 40000+ records
          net.sqlcipher.database.SQLiteStatement sqLiteStatement  = db.compileStatement(sqlBuffer.toString());
          sqLiteStatement.executeInsert();
    }
    db.setTransactionSuccessful();
    db.endTransaction();
```

**Comment by developernotes** [comment]
Hi @gunC 

The link that @baskarsk provided shows the Dalvik GC loop may likely be the cause of this. Since it appears you are inserting a rather large number of entries within a single transaction, you might consider batching those up into several smaller transactions to see if that helps address the issue.

**Comment by gunC** [comment]
Thanks @developernotes 
`batching those up into several smaller transactions` can run  normally!
Cipher cost more time then Android's Sqlite.

**Comment by developernotes** [comment]
Hi @gunC 

I'm glad to hear that worked!

**Comment by qiyongqiang** [comment]
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:813)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:846)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1175)
  at java.util.concurrent.locks.ReentrantLock$FairSync.lock(ReentrantLock.java:195)
  at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:256)
  at net.sqlcipher.database.SQLiteDatabase.lock(SQLiteDatabase.java:496)
  at net.sqlcipher.database.SQLiteQuery.fillWindow(SQLiteQuery.java:64)
  at net.sqlcipher.database.SQLiteCursor.fillWindow(SQLiteCursor.java:290)
  at net.sqlcipher.database.SQLiteCursor.getCount(SQLiteCursor.java:271)
  at net.sqlcipher.AbstractCursor.moveToPosition(AbstractCursor.java:178)
  at net.sqlcipher.AbstractCursor.moveToFirst(AbstractCursor.java:222)
  at android.database.CursorWrapper.moveToFirst(CursorWrapper.java:65)
  at de.greenrobot.dao.AbstractDao.loadUnique(AbstractDao.java:154)
  at de.greenrobot.dao.AbstractDao.loadUniqueAndCloseCursor(AbstractDao.java:147)
  at de.greenrobot.dao.InternalQueryDaoAccess.loadUniqueAndCloseCursor(InternalQueryDaoAccess.java:25)
  at de.greenrobot.dao.query.Query.unique(Query.java:118)

**Comment by developernotes** [comment]
Hi @qiyongqiang 

What version of SQLCipher for Android are you using? Are you able to recreate the issue as a unit test within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

**Comment by qiyongqiang** [comment]
@developernotes i'm use net.zetetic:android-database-sqlcipher:3.5.1, i can‘t recreate this issue as a unit test,this issue was found by bugly. are you some Suggestion？

**Comment by developernotes** [comment]
Hi @qiyongqiang 

I am not aware of what would cause that error to occur in your case. It would require further information such as the query that is attempting to run at the time, which is why I suggested you attempt to recreate the issue within the test suite. Also, it appears you are using a wrapper around SQLCipher for Android, you might try to rule that out as well.
