### ISSUE TITLE
upgrading from 3.1.0 to 3.3.0

### ISSUE THREAD

**Issue by dragosraducanu** [sqlcipher/android-database-sqlcipher#182]
I've successfully integrated the new SQLCipher into my app, but I'm having troubles while I perform an application update from v1 (which uses sqlcipher 3.1) to v2 (which uses sqlchiper 3.3).

My database is encrypted.

I get the following exception/logs:

`E/Database﹕ CREATE TABLE android_metadata failed
06-11 17:23:10.565    7968-8008/com.shell.sitibv.motorist E/Database﹕ Failed to setLocale() when constructing, closing the database
    net.sqlcipher.database.SQLiteException: file is encrypted or is not a database
            at net.sqlcipher.database.SQLiteDatabase.native_setLocale(Native Method)
            at net.sqlcipher.database.SQLiteDatabase.setLocale(SQLiteDatabase.java:2096)
            at net.sqlcipher.database.SQLiteDatabase.<init>(SQLiteDatabase.java:1962)
            at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:881)
            at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:913)
            at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:132)`

Any tips?

**Comment by developernotes** [comment]
Hello @dragosraducanu 

Can you try using SQLCipher for Android from the current master branch?  There have been some changes integrated there that may provide a more useful error message.  Please let us know your results.  Thanks!

**Comment by dragosraducanu** [comment]
Thanks for the reply, @developernotes.
 
I tried that and the only new log that I get is:
 I/Database﹕ sqlite returned: error code = 26, msg = file is encrypted or is not a database

Thanks!

**Comment by developernotes** [comment]
Hello @dragosraducanu 

Have you verified whether the database file exists at the path provided to the library when you receive this error message?  Are you certain the correct password is being provided?  Can you pull the database off the device and verify the SQLCipher command line tool can properly open the database file?  Are you able to reliably recreate this behavior?  If so, could you add a test for further review to the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

**Comment by dragosraducanu** [comment]
Hi @developernotes,

I did not verify if the db exists at path, but I'm sure it is there because I'm also testing the app update without upgrading the sqlcipher and everything is fine. (same comment for the password). 

I will try to pull the database off the device to see if I can get more info. 
I'm currently manually testing and I'm able to reproduce it every time.  The way I'm testing is described below: 

I have 3 branches -> app_v_1, app_v_2_sqlcipher3, app_v_2_sqlcipher33
updating from first to second works fine every time;
updating from first to third fails every time;

Thanks!

**Comment by dragosraducanu** [comment]
Apologies for wasting your time on this. I was actually upgrading from sqlcipher < 3 and I needed to use PRAGMA cipher_migrate;

Thanks for helping out!

**Comment by developernotes** [comment]
Hi @dragosraducanu 

Thanks for updating us on your status, we are glad to hear you resolved the issue!

**Comment by brodybits** [comment]
Just a quick suggestion that this should be documented more clearly. I found the following post from last year that actually gives you the code, with a proper Apache license statement, how to migrate from sqlcipher < 3: http://blog.osom.info/2014/03/migrating-to-sqlcipher-for-android-3x.html

**Comment by developernotes** [comment]
@brodybits - do you feel it is missing from anywhere specific?  We try to provide coverage in many places when we make changes like this such as the SQLCipher Discuss site, blog, changelog within the repo, and the test suite.

**Comment by brodybits** [comment]
I would like to see a small note at the end of pages like https://www.zetetic.net/sqlcipher/sqlcipher-for-android/ and https://www.zetetic.net/sqlcipher/documentation/ since they show up when I do a quick Google search. Perhaps a page that describes how to handle the upgrade, for both C-API versions (including "desktop" and iOS versions) and the Android version (in Java), that the notes will link to. Also a small note at the end of both https://github.com/sqlcipher/sqlcipher (C-API project) and this project (Android-Java API).

A couple more nits (details):
- remove the old jars from https://www.zetetic.net/sqlcipher/sqlcipher-for-android/ (2 places)
- update copyright year

In addition, I suggest we omit the Javadoc jar from the generated `libs` (put it in a generated `javadoc` directory or something instead). I can work on a pull request for this when I get a chance.

In general I would like to thank the project owners for the efforts made to implement and support these libraries.
