### ISSUE TITLE
Add SQLiteOpenHelper#getDatabaseName method

### ISSUE THREAD

**Issue by alipov** [sqlcipher/android-database-sqlcipher#184]
Hi,

I wonder if you have any objection to adding this getter method for API compliance with Android's [SQLiteOpenHelper#getDatabaseName](http://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html#getDatabaseName()).
If you don't have any, I'd like to submit a pull request.

Thanks!
Alex.

**Comment by brodybits** [comment]
I leave this up to the project owners, but I personally do not like any more deviations than are absolutely necessary from the standard Android sqlite database API. Such deviations would reduce portability to other Android database implementations, such as https://github.com/illarionov/android-sqlcipher-spatialite or even https://github.com/moneymanagerex/SQLite-Android-Bindings (which I do not recommend since it does not have an explicit license statement).

**Comment by alipov** [comment]
@brodybits 
What is your definition for *standard Android sqlite database API*?
Mine is - classes under AOSP's [android.database.sqlite](http://developer.android.com/reference/android/database/sqlite/package-summary.html) package. 
That is, if I'm switching from Android's standard API to SQLCipher, I expect for minimum changes.

**Comment by brodybits** [comment]
My apologies @alipov, you are right that this _is_ part of the "standard" Android sqlite database API. It was introduced in API 14 which seems to be Android 4.0 ICS. It _may_ (or may not) help you to see how they did it in the Android database source code and see how can be reused verbatim in this project.

**Comment by developernotes** [comment]
Hi @alipov 

We generally have avoided these type of changes in the past (however we have made them before).  The issue is that we support Android down to 2.1 in which that specific API call was not introduced yet (per @brodybits comment above).  Are you unable to access the name any other way within your application?  Can you explain your specific need for this feature?

**Comment by alipov** [comment]
Hi @developernotes 
I can understand why you hesitate to make such changes. But I think that by supporting 2.1 you shouldn't neglect introduction of new functions from more advanced APIs.
The framework annotates those (new) methods with [TargetApi](http://developer.android.com/reference/android/annotation/TargetApi.html), so why not to follow the same practice? After all, such changes are not going to break things..

As for me, I'm messing a lot with converting applications from standard sqlite API to an encrypted one, and each incompatibility noticeable right away :)

**Comment by brodybits** [comment]
@alipov if we make the changes, my personal preference is that the changes should just work regardless of which version of the Android system it is running on. Since this project is essentially replacing the built-in Android database classes for the case of sqlcipher, I cannot see why this should be an issue. Just make sure we do not introduce any dependencies on newer API versions of the built-in Android classes and I think we should be OK.

**Comment by developernotes** [comment]
I agree with @brodybits, in order to add this feature, it must be available from the base API support and up (i.e., 2.1).
