### ISSUE TITLE
Crash on Android 6.0 emulator

### ISSUE THREAD

**Issue by TomAtRB** [sqlcipher/android-database-sqlcipher#190]
I am getting a crash on launch when trying to test on an Android 6.0 emulator 

java.lang.UnsatisfiedLinkError: dlopen failed: ... lib/x86/libsqlcipher_android.so: has text relocations

Using:
sqlcipher-for-android-v3.3.1
Android emulator x86 API 23 (6.0)

**Comment by developernotes** [comment]
Hello @TomAtRB 

Are you certain you have integrated the library according to the documentation [here](https://www.zetetic.net/sqlcipher/sqlcipher-for-android)?  I was just able to run the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on the x86 emulator for API 23 successfully.
![screen shot 2015-08-21 at 4 42 51 pm](https://cloud.githubusercontent.com/assets/3225/9419754/1eb5f1a0-4824-11e5-8b78-2b62d19c6d61.png)

**Comment by TomAtRB** [comment]
I am able to replicate the crash in the test suite by updating the "targetSdkVersion" and "compileSdkVersion" to "23"

/net.zetetic E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    Process: net.zetetic, PID: 22424
    java.lang.RuntimeException: An error occurred while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:309)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/net.zetetic-1/lib/x86/libsqlcipher_android.so: has text relocations
            at java.lang.Runtime.loadLibrary(Runtime.java:372)
            at java.lang.System.loadLibrary(System.java:1076)
            at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:140)
            at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:135)
            at net.zetetic.tests.TestSuiteRunner.runSuite(TestSuiteRunner.java:36)
            at net.zetetic.tests.TestSuiteRunner.doInBackground(TestSuiteRunner.java:20)
            at net.zetetic.tests.TestSuiteRunner.doInBackground(TestSuiteRunner.java:12)
            at android.os.AsyncTask$2.call(AsyncTask.java:295)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)

**Comment by developernotes** [comment]
Hello @TomAtRB 

I was able to reproduce this by adjusting the `targetSdkVersion` and `compileSdkVersion`.  I will look into this.  Thanks!

**Comment by ErnestG** [comment]
@developernotes any chance it's because of

```
Android is moving away from OpenSSL to the BoringSSL library. If you’re using the Android NDK in your app, don't link against cryptographic libraries that are not a part of the NDK API, such as libcrypto.so and libssl.so. These libraries are not public APIs, and may change or break without notice across releases and devices. In addition, you may expose yourself to security vulnerabilities. Instead, modify your native code to call the Java cryptography APIs via JNI or to statically link against a cryptography library of your choice.
```

https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client

**Comment by developernotes** [comment]
Hi @ErnestG 

It is unlikely due to the libcrypto dependency.  We are actually building our own version of libcrypto and linking that directly into the library, so we are not dependency on any specific version of libcrypto being available on a given Android device.

**Comment by kmusham** [comment]
I am also getting the same error with the same environment. 
Did you find any solution or workaround yet?

**Comment by developernotes** [comment]
Hello @kmusham 

We are looking into the issue, at the time being we recommend that you do not target API 23 until this issue is resolved.

**Comment by jdzuri** [comment]
I have the same error too. I remain waiting for its solution. Thank you @developernotes for the info.

**Comment by developernotes** [comment]
Hi @TomAtRB, @ErnestG, @kmusham,

I have just pushed up a fix in the master branch that addresses the text relocation crash reported above.  Please take a look when you get the opportunity.  Thanks!

**Comment by jdzuri** [comment]
Hello @developernotes,

I've tested the library with the fix and work fine with the API 23 (emulator and hardware preview-3).

Thanks!

**Comment by developernotes** [comment]
Hi @jdzuri 

Thank you for reporting your success with the latest changes.

**Comment by powder366** [comment]
Where do I get the jniLibs files? The last version here is from Jul 13  v3.3.1. And here is also old https://www.zetetic.net/sqlcipher/open-source/ stuff. Or am I missing something?

**Comment by developernotes** [comment]
Hello @powder366 

We have just released the latest version of SQLCipher for Android, more information can be found [here](https://discuss.zetetic.net/t/sqlcipher-for-android-3-3-1-1-release/806).

**Comment by powder366** [comment]
Thanks worked great. It seems one don't need the ".so" files anymore?

**Comment by developernotes** [comment]
@powder366 you still need them, the .so files are bundled with the .aar package.

**Comment by maniacs-engineerica** [comment]
Hi, I am trying to apply this fix, but I don't understand. Does this bug only occurs in emulator? I don't have a real device with API 23.

Anyway, which files do I have to update in my project to add this fix solution?
Thanks!

**Comment by developernotes** [comment]
Hello @maniacs-engineerica 

The issue was verified within the emulator when running with a target SDK set to 23.  The specific commit that addressed the issue can be found here: 098ecdbcf2.

**Comment by maniacs-engineerica** [comment]
Thank you for your help. I am not sure on how to include new libcrypto.a in my project, can you help me?
Thanks!

**Comment by developernotes** [comment]
Hello @maniacs-engineerica 

The static libraries are already built into the binary distribution, you can just reference the AAR package that is available through jcenter or Maven Central.

**Comment by maniacs-engineerica** [comment]
That's perfect. It works! Thank you.

**Comment by sagarkakad** [comment]
I m having Android App that uses SQL cipher 2.2.0 library to encrypt the db. After Android 6.0 upgrade we updated to SQL cipher 3.3.1 since previous library was giving problem on android 6.0. After the sql cipher upgrade the app started working on android 6.0 as well. But the problem is it is not able to read the already encrypted DB (encrypted using cipher 2.2.0). 
It is giving following error 
" sqlite returned: error code =26, msg=file is encrypted or is not a database: 
CREATE TABLE android_metadata failed.
failed to setLocale() when constructing, closing the database.
create locale table failed.
old jar is

  compile file('build/intermediates/rs/debug/lib.sqlcipher.jar')
i am using following jar

compile 'com.android.support:support-v4:23.0.0'
compile 'net.zetetic:android-database-sqlcipher:3.3.1-1@aar'

Is it that encryption algorithm has changed or am i doing some mistake.

Please help.

**Comment by TheNephilim88** [comment]
Did you migrate your db to new v3-format?
https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_migrate

**Comment by developernotes** [comment]
Hello @sagarkakad 

@TheNephilim88 is correct, you will need to upgrade the database file to the new 3.x format using the `PRAGMA cipher_migrate;` command.

**Comment by sagarkakad** [comment]
how can i upgrade database file to new 3.x format using PRAGMA cipher_migrate; command

 please guide me...

**Comment by developernotes** [comment]
Hello @sagarkakad 

There is an example of the usage within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) [here](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/src/main/java/net/zetetic/tests/CipherMigrateTest.java).

**Comment by sagarkakad** [comment]
Thanks @developernotes & @TheNephilim88 .

I had to do few changes , 
- Instead of using the sqlcipher.jar provided in test suite i added following line in gradle file 
==> compile 'net.zetetik:android-database-sqlcipher:3.3.1-2@aar' 
before that it was giving error for net.sqlcipher.DatabaseErrorHandler

- The above link downloads the .SO files as well. I ignored those file and added the ones provided in test suite.

After this updates My APP is working :+1: , but I am facing 2 problem 
1. The App speed has slowed (the latency has increased by 5 times) . Not sure why because at code level there is no change except for migration to 3.3.1 cipher and that happens only once on SQLException.
2. APK size has increased. Not Sure but may be because of .SO file added for armeabi, armv7 & x86.

Please suggest me to sort out above problem. I am more concern about speed

Thanks Again!!! :+1:

**Comment by developernotes** [comment]
Hello @sagarkakad 

>Instead of using the sqlcipher.jar provided in test suite i added following line in gradle file 
==> compile 'net.zetetik:android-database-sqlcipher:3.3.1-2@aar' 

Just for clarification, the correct AAR reference name should be:

    compile 'net.zetetic:android-database-sqlcipher:3.3.1-2@aar'

>The above link downloads the .SO files as well. I ignored those file and added the ones provided in test suite.

It is **not** recommended that you mix and match jars and .so files from different distributions.  This behavior could certainly cause issues.  Is there a reason you are opting to not use the binaries distributed in AAR package provided?

With regard to the performance impact of SQLCipher within your application, I would recommend reviewing the SQLCipher performance guidance we have posted [here](https://discuss.zetetic.net/t/sqlcipher-performance/14).  The binary size of your application will increase due to the various components of SQLCipher.

**Comment by sagarkakad** [comment]
Hello @developernotes 

Thanks for support

When i am using sqlcipher 2.2 my app responds very fast, their is no time delay.  now i am replace only sqlcipher2.2 with sqlcipher 3.3.1 using 
compile 'net.zetetic:android-database-sqlcipher:3.3.1-2@aar'

because sqlcipher 2.2 it not supporting to Android 6.0 now my app with same code gets very slow.
i need to wait few seconds after every click then next operation perform.
how i overcome from this 
plz guide me ....... 


Thanks

**Comment by developernotes** [comment]
Hello @sagarkakad 

Have you reviewed the SQLCipher performance guidance provided [here](https://discuss.zetetic.net/t/sqlcipher-performance/14)?  If not, I would recommend evaluating your application to identify specifically where the slowness is occurring and make the appropriate adjustments.

**Comment by hendrysetiadi89** [comment]
compile 'net.zetetic:android-database-sqlcipher:3.3.1-2@aar'

give me error: 
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_40\bin\java.exe'' finished with non-zero exit value 2

**Comment by hendrysetiadi89** [comment]
Ahh. nvm..
I solved it. It is because it has conflict with the old jar. I have to clean and rebuild project.

Thank you very much.
This is Great.

**Comment by developernotes** [comment]
Hi @hendrysetiadi89 

Thanks for getting back to us, we are glad to hear the issue has been resolved.

**Comment by zamesilyasa** [comment]
I steel have the issue on 6.0 with 3.4.0

**Comment by McPo** [comment]
I too still have this issue.

However using http://slowbutdeadly.blogspot.co.uk/2015/09/javalangunsatisfiedlinkerror-dlopen.html

I noticed that the so files in the aar do not contain text relocations.
I then pulled the so file of the device and check if it had text relocations. It did.
I then realised Android Studio was still using the old so file.

However I had cleaned the build, deleted the build folders, invalidated the caches and recreated the VM. The old so file should therefore no longer be on the system, but its still manages to get installed in the app.

Basically the so file in the app is not the one in the aar. It must be cached somewhere but not sure were. Ill report back if I find a solution.

**Comment by greyowly** [comment]
@developernotes is there anything different with so file ? I run my apps on marshmallow device and using compile 'net.zetetic:android-database-sqlcipher:3.3.1-2@aar', it's working just fine ( no so file in the project ). But when i run the project into < marshmallow, i got the error db file is not a database or encrypted file. But when i add so file into the project, there's no problem with it. But when i run into Marshmallow, it give me error java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.grey.project/lib/arm/libstlport_shared.so: has text relocations

**Comment by developernotes** [comment]
Hello @greyowly 

The latest version of the library is currently 3.5.2, would you try that?
