### ISSUE TITLE
Android 6.0 support

### ISSUE THREAD

**Issue by zsoltboldizsar** [sqlcipher/android-database-sqlcipher#202]
Are there any chances to get support for Marshmallow as well somewhere in the near future?

**Comment by developernotes** [comment]
Hello @zsoltboldizsar 

Are you running into an issue on Android 6.0 with the library?

**Comment by zsoltboldizsar** [comment]
Yes, this is what I encounter for every user with M running on their devices:

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "EVP_CipherFinal" referenced by "/mnt/expand/b4d3fdf1-ed41-43e7-a163-c18fcf4f2e4b/app/net.quickbible-1/lib/arm/libsqlcipher_android.so"...
	at java.lang.Runtime.loadLibrary(Runtime.java:372)

**Comment by developernotes** [comment]
Hi @zsoltboldizsar 

What version of SQLCipher for Android are you using?  You should try updating to the latest version to see if that addresses your issue.

**Comment by zsoltboldizsar** [comment]
Unfortunately it's an old project, and really don't know what the lib version is. Back then, I took the binaries and built the source myself, and the result had no version included in their name... Is there something I've missed during the research a log or something after the lib got initialized? But anyway, I hope I'll have time to update the library and get back to you asap. Thanks in advance.

**Comment by developernotes** [comment]
Hello @zsoltboldizsar 

You can query the version of the library at runtime by executing the following SQL command:

    PRAGMA cipher_version;

It is difficult to say what exactly the cause of the issue is without more information.  An initial thought is that we used to dynamically link OpenSSL with the early versions of SQLCipher for Android.  We moved to static linking several years ago as the version of OpenSSL was inconsistent across OS versions.
