### ISSUE TITLE
native lib, increased application size approximately 13 MB.

### ISSUE THREAD

**Issue by rexi1r** [sqlcipher/android-database-sqlcipher#204]
@developernotes 
hey guy.
I have two question.

1.sqlcipher create folders x86 , armeabi , armeabi-v7a and put all native lib inside all of them so app size increase to 13mb.how can i reduce this size?

i have two another native lib :libSupportLibraries.so (Created by Me) and libp7zip.so.

libp7zip.so is inside armeabi folder but i know it's work with all kind of processor (i test this i seperated project and it work perfectly).

when i want to test my app on device with x86 processor(because of sqlcipher lib created x86 folder and android system search for x86 content for copy libs) i should copy libp7zip.so to x86 folder.
my app folder :
-  libs
  -  armeabi
    -  libp7zip.so
    -  libSupportLibraries.so
  -  x86
    -  libp7zip.so
    -  libSupportLibraries.so

but i got this error 
<code>
 Caused by: java.lang.UnsatisfiedLinkError: dlopen failed ..... libp7zip.so" has unexpected e_machine: 40
</code>

1. how can i reduce the app size(something like removing x86 folder but support all processor)?
2. How can I use the libp7zip.so but it is just be in armeabi folder(and my application work in all kind of processor)?.

**Comment by developernotes** [comment]
Hi @rexi1r 

>1.sqlcipher create folders x86 , armeabi , armeabi-v7a and put all native lib inside all of them so app size increase to 13mb.how can i reduce this size?

You can opt to only ship the target platforms you wish to support.  Including only armeabi will decrease your file size.

>when i want to test my app on device with x86 processor(because of sqlcipher lib created x86 folder and android system search for x86 content for copy libs) i should copy libp7zip.so to x86 folder.
but i got this error 
 Caused by: java.lang.UnsatisfiedLinkError: dlopen failed ..... libp7zip.so" has unexpected e_machine: 40 

You received that error because your copy of `libp7zip.so` was built to target armeabi, not x86.  The native libraries are architecture specific so you will need a copy of the library that was built for the x86 platform.

>how can i reduce the app size(something like removing x86 folder but support all processor)?

Do you need support for x86 devices?  If not, consider removing it if your application size is too large.  Also, you could consider removing the armeabi-v7a folder as the armeabi native libraries will be loaded on a armeabi-v7a device if the armeabi folder is present and the armeabi-v7a folder is not for your application.  We provide a public discussion site for free support on SQLCipher [here](https://discuss.zetetic.net/c/sqlcipher).

**Comment by rexi1r** [comment]
@developernotes 
hi.
first thanks for your answer but i mentioned earlier i test "libp7zip.so" on separated project and it work perfectly on x86 device and i know it's work with all kind of processor.
second how can i opt  targeting platforms?

**Comment by developernotes** [comment]
Hi @rexi1r 

>second how can i opt targeting platforms?

I'm not sure I understand what you are asking.  Public support is provided on our discuss site [here](https://discuss.zetetic.net/c/sqlcipher), please feel free to post more details there.  Thanks!
