### ISSUE TITLE
PRAGMA cipher command is deprecated, please remove from usage.

### ISSUE THREAD

**Issue by TheNephilim88** [sqlcipher/android-database-sqlcipher#224]
Hello,

as the new v3.4.0 includes changes from sqlcipher, that deprecates PRAGMA cipher and wont let it use anymore, I am wondering how to open/use/change cipher from existing databases that are not using the standard cipher "aes-256-cbc"?

All the best

**Comment by developernotes** [comment]
Hello @TheNephilim88 

The setter to `PRAGMA cipher` is still available in the 3.4.0 release.  In order to convert a database from one cipher to another you will want to use the `PRAMGA cipher_export` convenience function.  Example 3 in the [documentation](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) illustrates how the cipher can be changed when performing an export.

**Comment by TheNephilim88** [comment]
FYI and if anyone else is running in that problem:

It didnt work on my app as I executed PRAGMA cipher via execSQL. Changing to rawExecSQL did the trick.

You may should update the test case: https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/src/main/java/net/zetetic/tests/AES128CipherTest.java

**Comment by developernotes** [comment]
Hi @TheNephilim88 

The [test](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/src/main/java/net/zetetic/tests/AES128CipherTest.java) you reference works properly with the 3.4.0 release, did the test fail for you?

**Comment by TheNephilim88** [comment]
@developernotes I actually receive following error when using execSQL instead of rawExecSQL (I didnt test with test suite as it doesnt contain current version of the lib. my app used execSQL("PRAGMA cipher = 'blabla'"); in postKey-method for a long time and now suddenly didnt work anymore with 3.4.0):

net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here

**Comment by developernotes** [comment]
Hi @TheNephilim88 

My apologizes, I had a few local changes which I hadn't pushed up which included a change to calling `rawExecSQL(…)` instead.  The reason `exeSQL` fails now is because a result string is now being returned and the native function is [explicitly](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/jni/net_sqlcipher_database_SQLiteDatabase.cpp#L441) checking for `SQLITE_DONE`; it receives `SQLITE_ROW` due to the result string.  `rawExecSQL` does not throw an exception based on the status code.  I have pushed up my changes to the test suite.
