### ISSUE TITLE
First call "no such table" after copy from asset

### ISSUE THREAD

**Issue by protoss5482** [sqlcipher/android-database-sqlcipher#242]
net.sqlcipher.database.SQLiteException: no such table: city: /* sql request */
net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:83)
net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1758)
net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1723)

**Comment by theBlbDan** [comment]
'no such table' occurs when 1) There is no such table, 2) the database doesn't exist, 3) the database failed to open.  ```#3``` can happen if you try to open an encrypted DB providing an empty or incorrect password, or if you try to open an unencrypted DB and providing a password.

Honestly, your comment is very vague and assumes you didn't Google for any help yet.  Typically 'no such table' is due to programmer inexperience and not the library.  If you're having trouble using the library, opening an issue on Git is not very courteous.  [StackOverflow](http://stackoverflow.com/questions/4991368/sqliteexception-no-such-table) is better suited for this sort of thing.


What did you encrypt the DB with and how are you managing your DB in your app?  Have you checked that the file copy was successful?  Did you check that ```SQLiteDatabase.openDatabase()``` was successful?  Do you have the 'android_metadata' table in your DB?

**Comment by protoss5482** [comment]
I added after copying the database:
myDataBase.close();

Reopen the database, and it worked!

**Comment by theBlbDan** [comment]
Glad to see it is resolved.  Curious, what method, or process did you use for copying the DB file?

**Comment by protoss5482** [comment]
```
public void crateDatabase() throws IOException {
        if (!isDatabaseExist()) {
            this.getWritableDatabase(key);
            try {
                copyDataBase();
            } catch (IOException e) {
                throw new Error("Error copying database");
            }
            this.close(); // <-- Added db close
        }
    }
```

```
    private void copyDataBase() throws IOException {
        InputStream myInput = myContext.getAssets().open("databases/" + DB_NAME); 
        String outFileName = DB_PATH + DB_NAME;
        OutputStream myOutput = new FileOutputStream(outFileName);
        byte[] buffer = new byte[1024];
        int length;
        while ((length = myInput.read(buffer)) > 0) {
            myOutput.write(buffer, 0, length);
        }

        myOutput.flush();
        myOutput.close();
        myInput.close();
    }
```

**Comment by theBlbDan** [comment]
Ok, so why are you even opening the DB, especially right before performing the file copy?

```
public void crateDatabase() throws IOException {
   if (!isDatabaseExist()) {
      try {
         copyDataBase();
      } catch (IOException e) {
         throw new Error("Error copying database");
      }
   }
}
```


Check this out, it may or may not suite your needs.  FileUtils is provided by org.apache.commons.io.
```
private void copyDataBase() throws IOException {
    InputStream myInput = myContext.getAssets().open("databases/" + DB_NAME); 
    String outFileName = DB_PATH + DB_NAME;
    FileUtils.copyInputStreamToFile(srcInput, outFileName);
}
```

Check out this quick tutorial on using singletons.   Pay attention to Approach 1
[Use a Singleton to Instantiate the SQLiteOpenHelper](http://www.androiddesignpatterns.com/2012/05/correctly-managing-your-sqlite-database.html)

Also, make sure to close this ticket.

**Comment by amirhossein320** [comment]
this.getWritableDatabase();     solved   the  my problem      before  i  used  this.getReadableDatabase();
