### ISSUE TITLE
Cursor read semantics differ from stock SQLiteCursor

### ISSUE THREAD

**Issue by FrankSalad** [sqlcipher/android-database-sqlcipher#270]
In [stock Android](http://androidxref.com/4.2.2_r1/xref/frameworks/base/core/java/android/database/sqlite/SQLiteCursor.java#138) subsequent calls to `fillWindow` will not update `mCount` after the first time it is set. This differs from the behavior of sqlcypher's [fillWindow](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/src/net/sqlcipher/database/SQLiteCursor.java#L276) implementation. It leads to strange behavior when a reader executes a query, stores the number of expected results using `cursor.getCount` and then iterates more than that number of times when using `moveToNext`.

```
// cursor = getReadableDatabase().query(...)

String[] values = new String[cursor.getCount()];

for(int i = 0; cursor.moveToNext(); i++) {
    values[i] = cursor.getString(0);
}

// cursor.close()
```

Works fine with stock sqllite, but occasionally throws an `IndexOutOfBoundsException` with sqlcypher.

**Comment by developernotes** [comment]
Hi @FrankSalad 

Is this something that you can replicate within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? If so, we would be happy to look into this further. Thanks!

**Comment by draak567** [comment]
The problem starts happening when you have thousands of rows (enough that they don't all fit into  the cursor window) into a database table that is asynchronously changed by other threads. An example would be a mail client's Inbox list which continuously and unpredictably changes as mails arrive in the background.

Moving the cursor position may call fillWindow() which causes the cursor count to update. If the code is not designed to expect a different row count every time the cursor position is changed, problems may occur.

In particular, the legacy Android code convention of using a CursorAdapter with a ListView suffers from this problem. Your ListView will randomly crash if the table row count changes as the user is scrolling near the bottom of the list.

Adapting a cursor for a list view in this manner was thankfully not included with the newer RecyclerView, but that hasn't stopped folks from creating RecyclerView adapters that again attempt to pass the data directly from a cursor to a RecyclerView. They will also randomly crash; but the RecyclerView is a bit more informative (it will tell you that your dataset count changed without you calling notifyDataSetChanged() and to please check your logic).

The bottom line is, even if this was "fixed" it wouldn't solve the root of the problem - by the time you're trying to fill the window of the cursor, the data you expect to be there has changed. Suppose you have some code that takes you 1 minute to iterate through 10,000 rows in a cursor (that don't fit in a single window), but by the time you're at the end, 50 of those rows are gone. If the code expects exactly 10,000 rows to be there, you're going to have a bad time. That's what the issue is in the original post.

I would look instead at the design of the application, namely:

1) Do you really need all the rows? Can you just query a subset of the rows? This is especially relevant if you're displaying the results to a user. Does the user really need all 10,000 rows visible on a mobile device? Can you just load, say, 100, and then load more if they scroll down? It may not even be possible to physically scroll through all those rows anyway.
2) If you actually need all the data from the database in memory loaded at once, you can use dynamic structures like an ArrayList instead of a fixed array. This would ensure that no matter how many rows you actually get from your database, the code won't crash.
3) Do not use a cursor directly as an input to a ListView or RecyclerView unless you are sure the cursor results will always fit into a cursor window. Use an intermediate adapter that loads the cursor first to ensure consistency.
