### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed: library "libbacktrace.so" not found

### ISSUE THREAD

**Issue by zpapp** [sqlcipher/android-database-sqlcipher#272]
I've got a crash report from a user running Android 7.1 on a Google Pixel phone with the following stack trace:

`java.lang.UnsatisfiedLinkError: dlopen failed: library "libbacktrace.so" not found
at java.lang.Runtime.loadLibrary0(Runtime.java:989)
at java.lang.System.loadLibrary(System.java:1530)
at net.sqlcipher.database.SQLiteDatabase.loadLibs(SourceFile:174)
at net.sqlcipher.database.SQLiteDatabase.loadLibs(SourceFile:169)`

We have several other users on the same Android version and some even using the same device model who don't experience this problem.

We are using version 3.3.1-2 of SQLCipher. Is this a know issue? Has it been perhaps resolved in the most recent version of SQLCipher?

**Comment by developernotes** [comment]
Hello @zpapp 

We released an urgent and mandatory release of SQLCipher for Android [earlier this summer](https://www.zetetic.net/blog/2016/6/23/sqlcipher-android-release-n-support/) to add support to Android 7. We have since released several patch version, you can find instructions for using the latest package [here](https://www.zetetic.net/sqlcipher/sqlcipher-for-android). Please try the latest release to see if it resolves your issue.

**Comment by zpapp** [comment]
Yes it did, thanks!
