### ISSUE TITLE
NDK r13 support

### ISSUE THREAD

**Issue by Stoff81** [sqlcipher/android-database-sqlcipher#276]
Hi,

Do you have a timeline for when r13 will be supported? I need to upgrade our environment now. Im happy to look into the work required if someone can point me in the right direction?

Tom

**Comment by developernotes** [comment]
Hello @Stoff81 

We do not have any immediate plans to update the NDK build at the moment. Is there a specific issue with SQLCipher for Android that you are facing?

**Comment by Stoff81** [comment]
Hi @developernotes

I'm wantin to move our CI over to bitrise which only supports the latests NDKs. Would it be possible to just use prebuilt sqlcipher library built with r11 and keep my project using the latest? Given the recent changes to switch over to clang not sure if this would work

**Comment by developernotes** [comment]
Hi @Stoff81 

>Would it be possible to just use prebuilt sqlcipher library built with r11 and keep my project using the latest?

That is something you could perform on a one-off basis, however it would not be a supported approach. Do you have changes to the Java API? We have received reports of crashes due to others running development builds of SQLCipher for Android using the 12.x Android NDK toolchain. While the 13 series may resolve those issues, we will not likely jump head first into a change without further investigation.
