### ISSUE TITLE
can not support left out join?

### ISSUE THREAD

**Issue by ZhangPeibin** [sqlcipher/android-database-sqlcipher#300]
select a.*,b.*,c.* from rcontact a,img_flag b,userinfo2 c where a.username = b.username and  c.sid = 'USERINFO_SELFINFO_SMALLIMGURL_STRING' and a.username = 'wxid_0ya10zpdmaz312'.
I use this sql to query cursor.but some data missing .....

**Comment by developernotes** [comment]
Hi @ZhangPeibin 

I believe you are seeing this behavior due to join being performed within the WHERE clause, which causes side effects for LEFT JOIN or LEFT OUTER JOIN queries, unlike a JOIN, INNER JOIN, or CROSS JOIN in SQLite. Please take a look at the [WHERE clause filtering](https://www.sqlite.org/lang_select.html) section within the SQLite documentation.

**Comment by ZhangPeibin** [comment]
Thanks !
