### ISSUE TITLE
The problem of compiling with icu

### ISSUE THREAD

**Issue by andyken** [sqlcipher/android-database-sqlcipher#312]
I add -DSQLITE_ENABLE_ICU in the makefile.then make init and make.But the error is undefined reference to "utf8_nextCharSafeBody_55".I search the stackoverflow,this [page](http://stackoverflow.com/questions/6578600/how-to-compile-sqlite-with-icu) says set the LDFLAGS and CPPFLAGS.it don't work.This [page](http://stackoverflow.com/questions/14875047/linking-error-undefined-reference-to-icu-50unicodestringunicodestring ) says compile the icu with ./runConfigureICU Linux --enable-static --disable-shared --disable-renaming.then make the sqlcipher,But when i try it,it also says:reference to `utf8_nextCharSafeBody.Why?

**Comment by developernotes** [comment]
Hello @andyken 

ICU support has been removed from the library. Due to the complex nature of the build in conjunction to ICU, we do not provide public support for non-standard builds. If your organization is interested in licensing a custom build of SQLCipher for Android, please feel free to reach out to us at [support@zetetic.net](mailto:support@zetetic.net). Thanks!

**Comment by andyken** [comment]
@developernotes Is it free? if not, May I ask how much?

**Comment by developernotes** [comment]
Hello @andyken 

SQLCipher for Android is available in our community edition which is available at no charge. A customized version of the library would need to be licensed separately. Please reach out to us at [support@zetetic.net](mailto:support@zetetic.net) to discuss licensing further. Thanks!
