### ISSUE TITLE
SQL injection vulnerability

### ISSUE THREAD

**Issue by anon8675309** [sqlcipher/android-database-sqlcipher#342]
Line 300 of DatabaseUtils.java has a textbook SQL injection vulnerability.  
https://cwe.mitre.org/data/definitions/89.html

The appendEscapedSQLString() is also suspect, however I have not personally written an exploit to demonstrate this.

SQLite has the ability to separate data and queries which will ensure these issues do not occur.  If parameterized queries are used, there will not be any issues with SQL injection.  Doing so will require changing the API, as right now the interface if forcing users to mix code and data.
https://sqlite.org/lang_expr.html#varparam

**Comment by sjlombardo** [comment]
Hello @anon8675309 Thanks for getting in touch about this. This method was extracted directly from the AOSP project source, as was appendEscapedSQLString(), and is part of the [public Android Database API](https://developer.android.com/reference/android/database/DatabaseUtils.html). It's worth noting that concatenateWhere is not even used internally by the wrapper library, so would not create any vulnerability by default. That method would only be subject to a SQL injection vulnerability if the calling application were to use it to append user-supplied SQL parameters, in which case the behavior would be no different than using unsanitized SQL directly through the query interface. 

In practice Android.Database.SQLCipher already provides a separate mechanism to use parameterized queries so that applications can use binding.
