### ISSUE TITLE
FTS3/4 MATCH not supported?

### ISSUE THREAD

**Issue by nappy** [sqlcipher/android-database-sqlcipher#35]
In the sqlcipher documentation I read, that one should favor FTS over LIKE for performance. I wonder why I get the following error. I reduced my real world example to this simplified case:

Schema:
`CREATE VIRTUAL TABLE sites USING fts4(domain, url, title, meta_keys, body)`
`CREATE TABLE keywords (keyword TEXT)`

Query:
`SELECT keyword FROM keywords INNER JOIN sites ON sites.title MATCH keywords.keyword`

I get a info.guardianproject.database.sqlcipher.SQLiteException: "SQL logic error or missing database".

info.guardianproject.database.sqlcipher.SQLiteQuery.native_fill_window(Native Method)
info.guardianproject.database.sqlcipher.SQLiteQuery.fillWindow(SQLiteQuery.java:73)
info.guardianproject.database.sqlcipher.SQLiteCursor.fillWindow(SQLiteCursor.java:290)
info.guardianproject.database.sqlcipher.SQLiteCursor.getCount(SQLiteCursor.java:271)
android.database.CursorWrapper.getCount(CursorWrapper.java:51)

**Comment by nikhilmahesh** [comment]
I am facing similar issue.

Query with MATCH not returning any results:
SELECT call_id, caller, recipient, start_time, end_time FROM call_record WHERE caller MATCH 'j*';

Query with LIKE is providing Results:
Select * from Call_record where caller LIKE 'j%';

https://stackoverflow.com/questions/44304688/match-keyword-full-text-search-not-working-with-sqlite3-c-api

**Comment by sjlombardo** [comment]
@nikhilmahesh were you able to run the test case that @developernotes mentioned in the earlier post? Does your example work if you create using `fts4` instead of `fts3`?

**Comment by nikhilmahesh** [comment]
@sjlombardo : I was able to do it with FTS5 instead.

**Comment by sjlombardo** [comment]
@nikhilmahesh I'm glad to hear that fts5 worked for you. I don't think the tokenizer should have any impact on the behavior in this case, since each column is a single term and it shouldn't affect the substring MATCH functionality. Since it sounds like you are using the C API directly, I have a few other questions:

1. Are you using a packaged version of SQLCipher for Android, or one you built yourself?
2. If the former, what version of SQLCipher for Android are you using? 
3. If the latter, what build flags are you using to compile the library?
4. Are you able to reproduce this in a standalone test for the SQLCipher for Android test suite? https://github.com/sqlcipher/sqlcipher-android-tests
