### ISSUE TITLE
Open Wechat db

### ISSUE THREAD

**Issue by ZhangPeibin** [sqlcipher/android-database-sqlcipher#351]
### Expected Behavior
open wechat db success with right password

### Actual Behavior
In rare cases it open failed with right password

Can you tell me answer? or give me a direction.

**Comment by theBlbDan** [comment]
## Expected Behavior
When posting an issue to github, user provides logcat output and code sample of the point of failure.

## Actual Behavior
User just says, "It broke.  Why?"

On a serious note, you cannot expect somebody to understand why your code fails if you do not provide a stack trace and code sample where the stack trace says your app crashed.  Every developer thinks their code is golden and it's the fault of some library they included.  Still to this day I find places where I either misunderstood how to use something, or I simply fell asleep at the wheel and did it wrong.

If it is SQLCipher that is breaking, you have to show sufficient evidence (your code & stack trace) to prove that.  More than likely, you're using it incorrectly.  This isn't a personal attack, it's just that proven of a library and there are a few things you have to do absolutely correctly to make SQLCipher perform.

If you want some guidance on how to use SQLCipher, there are some excellent write ups, but it varies depending on what you're wanting to accomplish and your coding techniques and styles.


-peace

**Comment by ZhangPeibin** [comment]
It's my fault.Thanks !

**Comment by ZhangPeibin** [comment]
@theBlbDan Thanks ! I will do the next thing!
