### ISSUE TITLE
cursor.getInt() method returns 0 of column as TEXT having '08' value

### ISSUE THREAD

**Issue by honglai** [sqlcipher/android-database-sqlcipher#373]
### Expected Behavior
int wk = cursor.getInt(c.getColumnIndex("CUR_STD_WK"));  // column has 08  as TEXT
hope 8, but always return  0, but 05 returns 5, so strange !
### Actual Behavior
column has 08 as text,  the getInt has to return 8 as int.
following getString is right.
String wk = cursor.getString(c.getColumnIndex("CUR_STD_WK"));  
then wk value is 08 as String. only getInt failed
### Steps to Reproduce
1. make TEXT column
2. set value from 01 to 10
3. some values return 0 like '08'

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):
3.5.7
SQLCipher for Android version:
3.5.7
*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hi @honglai,

When SQLCipher for Android is attempting to interpreting your textual value of `"08"` as an integer, it is calling [`strtoll`](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/cpp/net_sqlcipher_CursorWindow.cpp#L135) within the cursor window. In our usage, the 3rd parameter to that function call allows the caller to specify the radix. We utilize the value of `0` in which the format of the input value is used to determine the numeric base. In this case, a leading zero in your input value indicates an octal format, not decimal.

While it is possible to change this to force a radix of `10`, which appears to be what you are looking for, that would introduce a regression for users with content stored in alternative formats.

Since it appears you know that you will need an integer value from the column containing text, might I suggest adjusting your query to use a [`CAST`](https://www.sqlite.org/lang_expr.html#castexpr) instead:

```
SELECT CAST(a AS INTEGER) FROM t;
```
