### ISSUE TITLE
sqlcipher file is not a database: , while compiling: select count(*) from sqlite_master - ONLY ANDROID 8.0.0

### ISSUE THREAD

**Issue by matape** [sqlcipher/android-database-sqlcipher#434]
### Expected Behavior
The App should create database and start after the installation.

### Actual Behavior
The App crashes evertime and is not able to open. 
Clean installation without artifacts. 
ONLY happen on Android 8.0.0 devices.

### Steps to Reproduce

SQLCipher for Android version: 4.1.3

Just install and launch the app. 
Crashlog appended.
[Crashlog.txt](https://github.com/sqlcipher/android-database-sqlcipher/files/3025311/Crashlog.txt)

**Comment by developernotes** [comment]
Hi @matape 

Unfortunately, the stack trace you provided isn't enough to troubleshoot the problem you are experiencing. The `SQLiteException` you are receiving could be caused by many different reasons. For example, an invalid password would generate the same behavior.

Would you please post an example of the code you are trying to execute that causes the error? Are you able to run the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on the device/emulator you are experiencing issues with?

**Comment by vithunIROID** [comment]
Same issue here. 
net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
Error occur only on android PIE VERSION. 
Password is same
Code is working fine for below PIE
Checked with 3.5.9 and 4.1.3 version 
Please help me to sort out this issue. I don't know how to use test suite.
Below is my Code where error occur:
  File databasePath = context.getDatabasePath(DATABASE_NAME);
            mDatabase = SQLiteDatabase.openDatabase(databasePath.getAbsolutePath(), Constants.UNKNOWN_PWD, null, SQLiteDatabase.OPEN_READWRITE);

**Comment by matape** [comment]
Its wasn't an issue of the lib. The manifest file was using allowBackup="true". 
Setting to "false" solved the issue.
The old database was recovered with the new installation.

**Comment by vithunIROID** [comment]
> Its wasn't an issue of the lib. The manifest file was using allowBackup="true".
> Setting to "false" solved the issue.
> The old database was recovered with the new installation.

I tried, still the issue exists. The issue occur for initial installation also.

**Comment by sjlombardo** [comment]
@matape thank you very much for letting us know this is resolved and that the root cause was unrelated to SQLCipher.

@vithunIROID your problem may not be the same setting, but is likely due to a key / database mismatch. As this ticket demonstrates, SQLCipher doesn't randomly report "sqlcipher file is not a database" exceptions. If you are seeing that error, there is very likely some difference between the key you are using and the database you are opening. If you can provide a reproducible case that demonstrates a problem please open a separate ticket about it and we'll look into it further.
