### ISSUE TITLE
Sqlcipher-Android Native library crash

### ISSUE THREAD

**Issue by ravisarma** [sqlcipher/android-database-sqlcipher#462]
### Expected Behavior 
Shouldn't crash on libsqlcipher.so access

### Actual Behavior 
Crashes on libsqlcipher.so

### Steps to Reproduce 
Unknown. 

Affects a large number of users running Samsung Galaxy A50, Motorola One Vision

SQLCipher version: 4.0.x, **4.2.0**

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.boxer.email <<<
 
backtrace:
  #00  pc 00000000000f1ac8  /data/app/com.boxer.email-lLS0ApnpUlMo9pYsVrc81Q==/lib/arm/libsqlcipher.so (_armv7_tick)
 
 

<img width="967" alt="image001" src="https://user-images.githubusercontent.com/3171776/60899577-b4669200-a238-11e9-968b-b7a77e8541b0.png">
<img width="962" alt="image002" src="https://user-images.githubusercontent.com/3171776/60899578-b4669200-a238-11e9-8f17-4bde7103140d.png">

**Comment by developernotes** [comment]
Hello @ravisarma,

I wanted to provide an update from our end regarding the behavior you are receiving reports of. We tested the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on the Samsung Galaxy A50 device, both using our Commercial edition and Community edition of SQLCipher for Android. Both test suite runs pass all tests successfully on that device.

We have a few follow-up questions regarding your use case:

- Are you using the prebuilt Community or Commercial edition of SQLCipher for Android in your project?
- Are you building SQLCipher for Android yourself?
  - If so, do you have any modifications to the source?
  - What version of the Android NDK are you using?
  - What host platform are you using to build SQLCipher for Android?
  - What version of OpenSSL are you using?
  - Are you building OpenSSL yourself?
- Are you able to provide a small code sample that recreates the issue?
- Does your application include any other third-party libraries?
  - If so, do any of those libraries have a dependency on OpenSSL?

We would be happy to investigate this issue further, however without a reproduction case to evaluate, further analysis may be limited from our end. Given the wide deployment of SQLCipher for Android, this is the first we've heard of this issue, and the high number of reports your application is receiving in relation to it brings to question whether the issue is application specific in some capacity. We look forward to your answers and helping where we can. Thanks!

**Comment by ravisarma** [comment]
@developernotes  Thanks for your response and testing with the device. We tested it previous week on a A50 from amazon, but could not repro the crash with any of our Android Applications. There are 6 models of the device, so we were assuming that the NA model may not have that issue. We are trying to get a Moto One vision as well. 

- We are using the sqlcipher (think prebuilt community) from jcenter/maven. 
- No modifications of the library, we use as-is. 
- Our App does include native libraries of our own which uses Openssl 1.0.2. 

I understand that it is hard to go without a repro step. We have not yet found a device where we can reproduce the crash, but in the process of ordering a few and trying. Would keep you posted on our findings, thanks again for spending time on this issue.

**Comment by developernotes** [comment]
Hello @ravisarma,

>Our App does include native libraries of our own which uses Openssl 1.0.2.

I wonder if there is a potential conflict here. SQLCipher for Android is currently built with [OpenSSL 1.1.1b](https://github.com/sqlcipher/android-database-sqlcipher/tree/master/android-database-sqlcipher/src/main/external). Would it be possible to rebuild your own native libraries against 1.1.1b to see if the behavior is different?

**Comment by ravisarma** [comment]
We are able to reproduce this with A50 with our automation. Would debug a bit and share the updates shortly.

**Comment by sjlombardo** [comment]
@ravisarma is this the same A50 that you got on amazon or a different / international model?

**Comment by ravisarma** [comment]
This is the same A50 NA model. Seems like it crashes during usage not right after install, have to review the test-case to identify the steps to repro.

**Comment by brodybits** [comment]
What is the status of this one?

**Comment by sjlombardo** [comment]
@brodybits - we're still waiting to hear back with further details. To summarize, we obtained an A50 for testing as did the reporter. Both were able to execute the full test suite without issues or crashes. However, following that @ravisarma was able to get a crash using their application in some scenario which was not specified (outside of the official test suite). Their application also includes some other native dependencies that link to a different version of OpenSSL, which may be a contributing factor.

@ravisarma can you provide an update on where things stand with your troubleshooting? Were you able to narrow down what is triggering a crash?

**Comment by ravisarma** [comment]
Hi @brodybits  @sjlombardo, apologies for not being active on this thread. Issue looks to be what @brodybits mentioned earlier here (certain arm7 opcodes not being available). The crash was happening when A50 was running an APK which did not have arm64 sqlcipher libraries(only having arm7 so's) , once we had app upgraded to include both the architectures - we were not able to reproduce this issue.
Also this was intermittent (occured only during some automation runs), we are keeping it under watch to see if we observe it again. Meanwhile i would go ahead and close the issue. Thanks for all your support, really appreciate the active discussions in the forum.
