### ISSUE TITLE
Where clause with -1 in query not working

### ISSUE THREAD

**Issue by RahulRawat-95** [sqlcipher/android-database-sqlcipher#494]
select * from TableGrade where (:countryId = -1 or country_id = :countryId)
getAllGrades(countryId: Long, gradeId: Long)

Calling it with getAllGrades(163, -1) should give list with size at least 3 as it is giving in a browser but it's giving list with size 0. Please help!!!

**Comment by developernotes** [comment]
Hi @RahulRawat-95 

Are you able to reproduce the issue directly within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? If so, we'd be happy to look into it further. Thanks!

**Comment by RahulRawat-95** [comment]
No @developernotes I have not reproduced it with test suite I was just building apk with the same thing. If you would like I can share a repo code with you.

**Comment by developernotes** [comment]
Hello @RahulRawat-95 

The next step would be to determine if you are able to reproduce it independently from your application. We would suggest you attempt to recreate the scenario as a test within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests). This will help identify whether there is an issue with the library vs. an application issue.

**Comment by RahulRawat-95** [comment]
Hello @developernotes 
I have forked test suite and reproduced the same error on SupportSuiteRunner. I think there is no problem in the database itself but when working with room. I have removed all the other test cases and added my own in [https://github.com/RahulRawat-95/sqlcipher-android-tests.git](Repository). There are two tests specifically one with encrypted db and another with unencrypted db which return different results. Please take a look and ask if you need more details.

**Comment by lokeshvinsol** [comment]
Hello @developernotes I am facing the same issue. Any solutions yet?

**Comment by developernotes** [comment]
Hi @commonsguy,

We were able to reproduce the incorrect behavior described by @RahulRawat-95 with his sample [here](https://github.com/sqlcipher/android-database-sqlcipher/issues/494#issuecomment-589929066) utilizing Room with SQLCipher for Android. Can you comment as to how Room translates the `Query` annotation string value to parameter bindings? I think that may be the cause of the issue in this scenario.

For reference, we tried the following sample test (note the two bound parameters) using standard SQLCipher for Android which results in reporting two values correctly.

```
package net.zetetic.tests;

import net.sqlcipher.Cursor;
import net.sqlcipher.database.SQLiteDatabase;

import java.util.UUID;

public class SimpleQueryTest extends SQLCipherTest {
  @Override
  public boolean execute(SQLiteDatabase database) {
    database.execSQL("create table t1(a,b);");
    database.execSQL("insert into t1(a, b) values(?, ?);",
        new Object[]{UUID.randomUUID().toString(), "foo"});
    database.execSQL("insert into t1(a, b) values(?, ?);",
        new Object[]{UUID.randomUUID().toString(), "bar"});
    int count = 0;
    Cursor cursor = database.rawQuery("select * from t1 where a = ? or ? = -1;",
        new Object[]{-1, -1});
    if(cursor != null){
      while (cursor.moveToNext()){
        count++;
      }
      cursor.close();
    }
    return count == 2;
  }

  @Override
  public String getName() {
    return "Simple Query Test";
  }
}
```

**Comment by commonsguy** [comment]
I'm not going to be in position to try to get that forked test suite working for a while. If somebody could point me to the specific test(s) that are failing, that would help with my comments.

> Can you comment as to how Room translates the Query annotation string value to parameter bindings?

That is handled by [`BindingsRecorder`](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/java/net/sqlcipher/database/BindingsRecorder.java).

Specifically, IIRC, Room uses [this version of `query()`](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L2951-L2959). The parameters get bound up in the `SupportSQLiteQuery` that we get, and there is no API to get those bindings. With my independent SafeRoom, the only way I could figure out how to get this working was to have the `SupportSQLiteQuery` bind its parameters to something so I could access them. That is where `BindingsRecorder` came from.

I looked into trying to get rid of the `BindingsRecorder` as part of setting up the support DB stuff here in SQLCipher for Android, but I could not come up with a solution that didn't involve modifying `SQLiteProgram` and `SQLiteQuery`. I was taking a "modify SQLCipher for Android as little as possible" approach, and since `BindingsRecorder` seemed to be working, I left that in place.

In principle, you could have a package-private API on `SQLiteQuery` that exposes the bindings, then use that in the call to `rawQuery()`, bypassing the need for `BindingsRecorder`. Whether that helps, or whether the problem lies somewhere else (e.g., in how `rawQuery()` uses those bindings), I can't say without knowing more about the failing tests. Plus, it is possible that the particular version of Room that is being used is going down a different path within `SQLiteDatabase` than what I remember.

**Comment by commonsguy** [comment]
Since nobody got back to me on this, I am having to guess.

I cloned the test suite fork, ran the support tests, and [this test](https://github.com/RahulRawat-95/sqlcipher-android-tests/blob/master/app/src/main/java/net/zetetic/tests/support/EncryptedRoomTest.java) fails.

Unless I am missing something, the failure would appear to be in the test code itself, not in SQLCipher for Android.

This tests inserts two `ChildEntity` objects. Each has a `parentId` property that is being set to a valid parent ID, based on having previously inserted a `ParentEntity`. I would expect `parentId` to be `1`, given that we have a fresh database.

Then, the test queries for all children whose `parentId` is `-1` (the passed-in parameter) or `-1` (the hard-coded value in the `getAllChildrenForParent()` SQL). Since neither child has that value for `parentId`, the query returns no rows. And, that is what the test shows... but the test assumes that it should return all children, which I do not understand.

If I change:

```java
List<ChildEntity> allChildrenNegativeOne = room.testDao().getAllChildrenForParent(-1);
```

to:

```java
List<ChildEntity> allChildrenNegativeOne = room.testDao().getAllChildrenForParent(parent.id);
```

...then the test succeeds.

---

Running the main set of tests, I see that `NegativeCursorTest` fails. That is using `"parentId = ? or ? = -1;"` as a `WHERE` clause. Putting `;` in there is not a safe move, though removing this does not fix the test.

While this test fails, it may not be related to the `SupportSQLiteDatabase` support, as that form of `query()` is not one [offered by `SupportSQLiteDatabase`](https://developer.android.com/reference/androidx/sqlite/db/SupportSQLiteDatabase).

This replacement test, which uses one of the `SupportSQLiteDatabase` versions of `query()`, works:

```java
package net.zetetic.tests;

import android.database.Cursor;
import net.sqlcipher.database.SQLiteDatabase;
import net.zetetic.tests.support.EncryptedRoomTest;
import androidx.sqlite.db.SupportSQLiteDatabase;

public class NegativeCursorTest extends SQLCipherTest {

    @Override
    public boolean execute(SQLiteDatabase database) {
        SupportSQLiteDatabase db = database;


        database.execSQL("CREATE TABLE `ParentEntity` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `intValue` INTEGER NOT NULL, `floatValue` REAL NOT NULL, `doubleValue` REAL NOT NULL, `charValue` INTEGER NOT NULL, `boolValue` INTEGER NOT NULL)");
        database.execSQL("CREATE TABLE `ChildEntity` (`uuid` TEXT NOT NULL, `stringValue` TEXT, `parentId` INTEGER NOT NULL, PRIMARY KEY(`uuid`), FOREIGN KEY(`parentId`) REFERENCES `ParentEntity`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )");
        database.execSQL("INSERT INTO ParentEntity (id, intValue, floatValue, doubleValue, charValue, boolValue) VALUES ('1', '1337', '2.71828007698059', '3.14159', '120', '1')");
        database.execSQL("INSERT INTO ChildEntity (uuid, stringValue, parentId) VALUES ('8fa35fb0-969d-4a25-8404-271997f37483', 'Um, hi!', '1')");
        database.execSQL("INSERT INTO ChildEntity (uuid, stringValue, parentId) VALUES ('ff5f54a3-8499-4e00-8ec3-3654055ac47e', 'And now for something completely different', '1');");
        Cursor cursor = database.rawQuery("SELECT * FROM ChildEntity;", new EncryptedRoomTest.ChildEntity[]{});
        Cursor cursorNegativeOne = db.query("SELECT * FROM ChildEntity WHERE parentId = ? or ? = -1;", new Object[]{"-1",-1});
        if (cursor != null && cursorNegativeOne != null) {
            return cursor.getCount() == cursorNegativeOne.getCount();
        }
        return false;
    }

    @Override
    public String getName() {
        return "Negative Cursor Test 1";
    }
}
```

So, I am not certain what to tell you.

**Comment by sjlombardo** [comment]
Hello @RahulRawat-95 - can you please review the above comments on this ticket, specifically the analysis by @commonsguy, and tell us more about what you are trying to do? Are you trying to retrieve all rows by effectively having the literal -1 match the bound value of -1? Or something else?

**Comment by RahulRawat-95** [comment]
Hello @sjlombardo so my use case is that I wrote some queries that should return all rows or some rows that matches the where clause so I used a short circuit or in the where clause that will return true for a value I give like -1 so I can have the same query or method in case of room return both types of data depending on it. As for @commonsguy answer I have used the same dao method's in default sqlite and it has worked every single time but it doesn't on sqlcipher which is crucial for the project I've been working on.  

`@Query("SELECT * FROM ChildEntity WHERE parentId = :id or :id = -1")
fun getChilds(id:Int)`

So when I call
`getChilds(-1)`
it returns all the rows in the ChildEntity table as the second condition in the where clause returns true for all cases which in turn makes all the rows eligible to be returned and also it is happening in the default version not in SqlCipher

**Comment by commonsguy** [comment]
@RahulRawat-95 My apologies for mis-reading the test. Upon further analysis, it appears as though SQLCipher is not liking the comparison of the parameter with a constant.

(for all of the following code snippets, assume the DAO function is called with `parentId` and `otherValue` both set to `-1`)

What you have in the test fails:

        @Query("SELECT * FROM ChildEntity WHERE parentId = :parentId or :parentId = -1")
        abstract List<ChildEntity> getAllChildrenForParent(long parentId);

This too fails:

        @Query("SELECT * FROM ChildEntity WHERE parentId = :parentId or :otherValue = -1")
        abstract List<ChildEntity> getAllChildrenForParent(long parentId, long otherValue);

This one succeeds:

        @Query("SELECT * FROM ChildEntity WHERE parentId = :parentId or :otherValue = :parentId")
        abstract List<ChildEntity> getAllChildrenForParent(long parentId, long otherValue);

This also succeeds:

        @Query("SELECT * FROM ChildEntity WHERE parentId = :parentId or (:parentId + 1) = 0")
        abstract List<ChildEntity> getAllChildrenForParent(long parentId);

Personally, I would not hack this into the SQL and would use a DAO method to call the appropriate generated method:

        List<ChildEntity> gimme(long parentId) {
            if (parentId == -1) {
                return getAllChildren();
            }
            else {
                return getAllChildrenForParent(parentId);
            }
        }

So, in the short term, you have some alternatives that you can use (the `(:parentId + 1) = 0` one or the `gimme()` DAO method). 

---

@developernotes AFAICT, the problem is not with the `SupportSQLite*` changes. If I change the test logic to this:

        SQLiteDatabase db = (SQLiteDatabase)room.getOpenHelper().getReadableDatabase();
        String[] projection = new String[] { "*" };
        String[] args = new String[] { "-1", "-1" };
        Cursor c = db.query("ChildEntity", projection, "parentId = ? or ? = -1", args, null, null, null);

        //the query should have returned both the list with same sizes here
        if (allChildren.size() != c.getCount()) {
            result.setResult(false);
            result.setMessage(String.format("expected all children, found %d from entity and %d from main query", c.getCount(), allChildren.size()));
            return result;
        }

...then we also fail. This is using a classic form of `query()` and AFAIK should not be impacted by the changes that we added for Room support.

However, this succeeds:

        SQLiteDatabase db = (SQLiteDatabase)room.getOpenHelper().getReadableDatabase();
        String[] projection = new String[] { "*" };
        String[] args = new String[] { "-1" };
        Cursor c = db.query("ChildEntity", projection, "parentId = ? or -1 = -1", args, null, null, null);

        //the query should have returned both the list with same sizes here
        if (allChildren.size() != /*allChildrenNegativeOne.size()*/ c.getCount()) {
            result.setResult(false);
//            result.setMessage(String.format("expected all children, found %d from entity and %d from main query", allChildrenNegativeOne.size(), allChildren.size()));
            result.setMessage(String.format("expected all children, found %d from entity and %d from main query", c.getCount(), allChildren.size()));
            return result;
        }

So, as with the Room scenarios, the problem seems to be with the parameter-to-constant comparison. To me, this feels like a core SQLCipher problem, but I might be missing something.

**Comment by developernotes** [comment]
Hi @commonsguy,

I wanted to provide an update on our findings and get your feedback on our proposed changes to address this issue. The issue appears to be related to the loss of data type information through the use of `BindingsRecorder`. While the `BindingsRecorder` allows for the capture of parameters via implementing `SupportSQLiteProgram`, the type information is lost when the call to `getBindings()` is invoked (i.e., it returns  a `String[]` by invoking `toString()` on each value), for the purposes of forwarding on the parameters to the `query` function.

The following example query binds the `:id` parameter as a string value using the `BindingsRecorder`, thus `"-1" != -1` and no rows match the fall-through condition of the query. We have verified the behavior of the query in isolation via a standalone C program. 

```
select * from t1 where id = :id or :id = -1
```

Our thought would be to utilize the existing `SQLiteQuery` implementation to bind the parameter values directly to the `sqlite3_statement` from the `SupportSQLiteQuery`. This approach allows the binding of datatypes to maintain their intended type as `SQLiteQuery` implements `SupportSQLiteProgram` already, so `BindingsRecorder` is no longer necessary. For reference, the current implementation of `query` can be found [here](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L2951-L2959). The result allows @RahulRawat-95 tests to pass, along with all other Support API tests within the test suite.

```
@Override
public android.database.Cursor query(final SupportSQLiteQuery supportQuery,
                                     CancellationSignal cancellationSignal) {
  String sql = supportQuery.getSql();
  int argumentCount = supportQuery.getArgCount();
  Object[] args = new Object[argumentCount];
  SQLiteDirectCursorDriver driver = new SQLiteDirectCursorDriver(this, sql, null);
  SQLiteQuery query = new SQLiteQuery(this, sql, 0, args);
  supportQuery.bindTo(query);
  return new CrossProcessCursorWrapper(new SQLiteCursor(this, driver, null, query));
}
```

Would you mind offering any feedback on this approach? Given your deep familiarity with the Support library, we wanted to make sure this implementation wouldn’t produce any unintended consequences.

Thank you,

**Comment by commonsguy** [comment]
If that works, that seems like it would be OK.

Waaaaaaaaaaaaay back in the beginning, `getArgCount()` didn't exist. That's what triggered my need for `BindingsRecorder`. [I asked them to add it](https://issuetracker.google.com/issues/67038952), got rejected, and then later they did wind up adding it. I missed that in SafeRoom and missed that again when implementing this stuff directly in your project. :frowning_face: 

The scenario that I mentioned from [my previous comment](https://github.com/sqlcipher/android-database-sqlcipher/issues/494#issuecomment-602110931) used a `String[]` variant of `query()`, which is why it too failed. Presumably, that is "working as intended", insofar as that's what the old API called for.

**Comment by developernotes** [comment]
Hi @commonsguy 

Thank you for the quick response, we are happy to hear this approach is viable. The usage of `getArgCount()` could be removed, but would require additional adjustments to the `SQLiteQuery` implementation that aren't necessary at this time.

We will look to integrate our changes into `master`, to be included in our next public release. Thanks again!

**Comment by developernotes** [comment]
Hi @RahulRawat-95 

I have just pushed a [change](https://github.com/sqlcipher/android-database-sqlcipher/commit/23325436094c08f39dc704a851d2c989bfb6783e) which addresses this issue. You are welcome to build it locally if you wish, otherwise this fix will be included in our next public release. Thank you for brining this to our attention.

**Comment by RahulRawat-95** [comment]
Thanks everyone. Will be waiting for the next release.
