### ISSUE TITLE
Help, could you give me some more information about openssl and libsqlciper.so？

### ISSUE THREAD

**Issue by jiangmingliu** [sqlcipher/android-database-sqlcipher#532]
hi, @sjlombardo @developernotes, recently i found [one security bugs](https://www.openssl.org/news/vulnerabilities.html) in openssl, in the sqlcipher aar package. in order to evalute the influence,  i do some work. i found a libsqlcipher.so in aar. Here is my questions. <br>
1.  what does the libsqlciper.so do? the functions;
2.  what role does  the openssl component play in the sqlcipher? 

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by jiangmingliu** [comment]
hi @developernotes ，could you please give me some reply?

**Comment by jiangmingliu** [comment]
hi @developernotes ，when you guys can release new version without this security bugs, as far as i know, the openssl has released new version [1.1.1i](https://www.openssl.org/news/vulnerabilities.html)

**Comment by sjlombardo** [comment]
Hello @jiangmingliu - SQLCipher does not use SSL / TLS or any asymmetric cryptographic functions. Therefore it is not affected by the CVE fixed in 1.1.1i related to X.509 GeneralName. That said we will update to the latest available OpenSSL version in the next release of SQLCipher, per our standard release process. I can't comment on a specific schedule for that release at this time.

If you have an urgent need to use a different version of OpenSSL now, you could either build OpenSSL and SQLCipher yourself from source, or contact us at sales@zetetic.net about the SQLCipher Enterprise program, under which we provide specialized builds to meet specific customer requirements.

**Comment by jiangmingliu** [comment]
thank you @sjlombardo, if you donnot use ssl/tls, why you build openssl within openssl？and what the functions of  libsqlcipher.so   in the aar?

**Comment by sjlombardo** [comment]
@jiangmingliu SQLCipher uses OpenSSL's libcrypto for symmetric cryptography (AES-256-CBC), HMAC (SHA1, SHA256, SHA512), PBKDF2 (HMAC-SHA1, HMAC-SHA256, HMAC-512) and a CSPRNG. You can find more information here: https://www.zetetic.net/sqlcipher/design/
