### ISSUE TITLE
SQLDatabase delete method gives Attempt to get length of null array

### ISSUE THREAD

**Issue by ksunil1920** [sqlcipher/android-database-sqlcipher#533]
If I call **delete(String table, String whereClause, String[] whereArgs) {}**  method by simply passing only table name and  **null** as whereArgs in SQLCipper version 4.3.0  where as in 3.5.9 version null was handled. 

Please fix this or else please suggest how to handle this.

**Comment by developernotes** [comment]
Hi @ksunil1920 

Have you tried the latest version of the software? This issue was [previously reported](https://github.com/sqlcipher/android-database-sqlcipher/issues/491) and a [fix](https://github.com/sqlcipher/android-database-sqlcipher/commit/bdf9fa71e8bdd3ee62dbdd2dcecf536abf4bb6cd#diff-fa99240cf3130ab4b9d25c14923ee2d6) has been added.

**Comment by ksunil1920** [comment]
I am using 4.3.0 and this issue is there in 4.3.0  and hopefully this is the latest public version.

**Comment by developernotes** [comment]
Hi @ksunil1920 

The latest version is [4.4.2](https://search.maven.org/artifact/net.zetetic/android-database-sqlcipher/4.4.2/jar). Please give that a try and let us know your results.

**Comment by ksunil1920** [comment]
Hi @developernotes ,
I tried with 4.4.2 and found it working. This issue has got fixed in 4.4.2.
Thank you so much.

**Comment by developernotes** [comment]
Hi @ksunil1920 

I am glad to hear that resolve the issue. Take care.
