### ISSUE TITLE
net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;

### ISSUE THREAD

**Issue by karan4c6** [sqlcipher/android-database-sqlcipher#547]
### Expected Behavior
The app should open.

### Actual Behavior
The app crashes before starting

### Steps to Reproduce
Open the app on Android 12 - os S version

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version: 4.4.2@aar

Are you able to reproduce this issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

*Note:* If you are not posting a specific issue for the SQLCipher library, please post your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
<img width="1622" alt="Screen Shot 2021-05-26 at 12 33 01 pm" src="https://user-images.githubusercontent.com/1883217/119594459-2ccf9f80-be1f-11eb-9f57-0f548151b1a6.png">

**Comment by theBlbDan** [comment]
From experience, I can tell you that you suffer from one of the three:
1. Your database file is not encrypted
2. Your file is not an SQLite file
3. The password you tried is incorrect
You may think the problem you face is an issue with the android-database-sqlcipher library, but it is a problem with your approach too using it. Go [here](https://www.zetetic.net/sqlcipher/sqlcipher-for-android/), and read, re-read, and read again.

**Comment by developernotes** [comment]
Hi @karan4c6,

If you are able to recreate the issue you are experiencing within the above referenced SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) we would be happy to look into the issue further. I have run the existing test suite against an Android OS S version emulator and all test pass successfully. The 3 scenarios that @theBlbDan mentions are the most likely cause of the behavior you are seeing otherwise.

**Comment by karan4c6** [comment]
Hi @theBlbDan  @developernotes 

Thanks for a quick response. Will try the mentioned three suggestions and revert with the findings, which hopefully might fix the issue !

**Comment by karan4c6** [comment]
Please keep it open for sometime I will update here soon.

**Comment by sunilcnair** [comment]
Hi All,

We checked through the code and the details mentioned here.. We need some support to understand on this error case which is crashig every time we launch on Android 12. As the new OS is releasing in Spetember, we need to identify this root cause on priority. Kindly support to get more understanding on this issue.

Also would be great to understand how to use the test sutie for testing the library.

**Comment by developernotes** [comment]
Hi @sunilcnair,

I see from your [response](https://github.com/sqlcipher/android-database-sqlcipher/issues/560#issuecomment-894985884) in the [other thread](https://github.com/sqlcipher/android-database-sqlcipher/issues/560) that a static key is preventing the crash from occurring. That is a good sign that the issue lies outside of the SQLCipher for Android library. Reviewing your post, you might consider ways in which you might rule out whether the key storage mechanism might be the cause of your issue, as providing an invalid key would prevent the library from accessing the database content. 

Our recommendation at this point would be to continue to isolate specific behaviors within your application to identify the root cause.

**Comment by sunilcnair** [comment]
@developernotes i see that you mentioned about the test suite working on Android S,  but google has suggested the root cause of the issue as 

Possible root cause:
net.sqlcipher.database seems to rely on an unsupported and undocumented feature of sqlite3: SQLITE_HAS_CODEC. SQLite (upstream) has removed this feature. Apparently, we updated the SQLite library to 3.32.2 in Android S which no longer has this feature

So i am confused on how this issue makes the library run on Android 12.

**Comment by sjlombardo** [comment]
@sunilcnair I think it would be best not to double-post comments to multiple issues. Since this issue is closed let's keep the discussion at the other ticket you opened:

https://github.com/sqlcipher/android-database-sqlcipher/issues/560
