### ISSUE TITLE
What is the OPENSSL version is used in 4.4.3 and 4.5.2. Vulnerabilities reported inn openssl

### ISSUE THREAD

**Issue by SunitaMK** [sqlcipher/android-database-sqlcipher#601]
Hi Team,

Please let me know which OPENSSL version is used  sqlcipher- 4.4.3 and sqlcipher-4.5.2 library buildings.
Our internal tool reporting multiple vulnerabilities in OPENSSL libraries.   We would like to know  are those vulnerabilities addressed in latest version of sqlcipher? Iff not whats the next plan?

*Note:* If you are not posting a specific issue for the SQLCipher library, please post your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hi @SunitaMK,

SQLCipher used OpenSSL 1.1.1j in [4.4.3](https://www.zetetic.net/blog/2021/03/02/sqlcipher-443-release/), and 1.1.1q in [4.5.2](https://www.zetetic.net/blog/2022/08/03/sqlcipher-4.5.2-release/). If you are a Commercial or Enterprise customer, please feel free to reach out directly to us directly at [support@zetetic.net](mailto:support@zetetic.net) for further assistance.

**Comment by tosulc** [comment]
@developernotes just a question. Why aren't you using [release notes](https://github.com/sqlcipher/android-database-sqlcipher/releases) (I see that you tag releases), so there won't be questions like this one? Or there will be, but it will be easier to communicate changes.

Btw. thanks for still supporting this lib. It's a game changer for database encryption in Android world.

**Comment by developernotes** [comment]
Hi @tosulc 

We do not use the GitHub Releases feature, we only distribute the Community edition binary artifacts via Maven Central. The changelog for the core library is here [^1], however, we are no longer bundling/versioning OpenSSL within the SQLCipher for Android library. Because of this, SQLCipher for Android may be built with different versions/configurations of OpenSSL. Typically, we annotate the version of OpenSSL used within the core library release notes instead. You can subscribe to our SQLCipher Updates discuss channel [^2] where we highlight the changes in new releases including the OpenSSL version.

[^1]: https://github.com/sqlcipher/sqlcipher/blob/master/CHANGELOG.md
[^2]: https://discuss.zetetic.net/c/sqlcipher/updates/14

**Comment by mohammadkhatri** [comment]
I was finding which openssl version is used in 4.4.0 but couldn't find in release notes. Is it using 1.1.1g or 1.1.1h ?

**Comment by KDisEDDY** [comment]
cause googleplay will check the openssl version，the old version dependency of 4.1.3 will refused，verion 4.5.2 is glad to update
