### ISSUE TITLE
Got the crash logs from playconsole

### ISSUE THREAD

**Issue by pateljay681** [sqlcipher/android-database-sqlcipher#651]
### Actual Behavior:- app crash due because of libsqlcypher.so

SQLCipher version (4.5.4`):

SQLCipher for Android version:

Are you able to reproduce this issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?
No, got the logs from play console

Logs:- 

[libsqlcipher.so] sqlite3_bind_text16

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 28833 >>> com.test.myapplications <<<

backtrace:
  Unknown
  #01  pc 0x00000000000dd224  /data/app/~~bMxqd5vaWbihl_GmVcO81Q==/com.test.myapplications-jeA1Foi17kS-2J7O3ZhBGg==/lib/arm64/libsqlcipher.so (BuildId: deda9f425883f98d89e336bb64e03330e87ed34f)
  #02  pc 0x00000000000dcf94  /data/app/~~bMxqd5vaWbihl_GmVcO81Q==/com.test.myapplications-jeA1Foi17kS-2J7O3ZhBGg==/lib/arm64/libsqlcipher.so (BuildId: deda9f425883f98d89e336bb64e03330e87ed34f)
  #03  pc 0x00000000000dd7b0  /data/app/~~bMxqd5vaWbihl_GmVcO81Q==/com.test.myapplications-jeA1Foi17kS-2J7O3ZhBGg==/lib/arm64/libsqlcipher.so (sqlite3_bind_text16+40) (BuildId: deda9f425883f98d89e336bb64e03330e87ed34f)
  #04  pc 0x00000000002407bc  /data/app/~~bMxqd5vaWbihl_GmVcO81Q==/com.test.myapplications-jeA1Foi17kS-2J7O3ZhBGg==/lib/arm64/libsqlcipher.so (BuildId: deda9f425883f98d89e336bb64e03330e87ed34f)
  #05  pc 0x00000000004224f0  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+128)
  #06  pc 0x00000000000c5ce4  /data/app/~~s3P2pcTIMZKNCqhVKENmvQ==/com.test.myapplications-OQeFU-5Aw21ssGtRvO0hig==/oat/arm64/base.odex

**Comment by developernotes** [comment]
Hello @pateljay681,

Unfortunately there is not enough information to diagnose a root cause with this stack trace alone. Additionally, the `android-database-sqlcipher` library has been [deprecated](https://github.com/sqlcipher/android-database-sqlcipher?tab=readme-ov-file#deprecated-library) in favor of [`sqlcipher-android`](https://github.com/sqlcipher/sqlcipher-android), the new long-term supported SQLCipher for Android library. We would recommend upgrading your library to `sqlcipher-android`.
